package mrs.domain.mapper;

import java.util.List;
import mrs.domain.model.MeetingRoom;
import mrs.domain.model.MeetingRoomExample;
import org.apache.ibatis.annotations.Param;

public interface MeetingRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    long countByExample(MeetingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    int deleteByExample(MeetingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    int deleteByPrimaryKey(Long roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    int insert(MeetingRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    int insertSelective(MeetingRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    List<MeetingRoom> selectByExample(MeetingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    MeetingRoom selectByPrimaryKey(Long roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    int updateByExampleSelective(@Param("record") MeetingRoom record, @Param("example") MeetingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    int updateByExample(@Param("record") MeetingRoom record, @Param("example") MeetingRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    int updateByPrimaryKeySelective(MeetingRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    int updateByPrimaryKey(MeetingRoom record);
}