package mrs.domain.mapper;

import java.util.List;
import mrs.domain.model.Reservation;
import mrs.domain.model.ReservationExample;
import org.apache.ibatis.annotations.Param;

public interface ReservationMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table reservation
     * @mbg.generated  Thu Jun 07 08:01:30 JST 2018
     */
    long countByExample(ReservationExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table reservation
     * @mbg.generated  Thu Jun 07 08:01:30 JST 2018
     */
    int deleteByExample(ReservationExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table reservation
     * @mbg.generated  Thu Jun 07 08:01:30 JST 2018
     */
    int deleteByPrimaryKey(Long reservationId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table reservation
     * @mbg.generated  Thu Jun 07 08:01:30 JST 2018
     */
    int insert(Reservation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table reservation
     * @mbg.generated  Thu Jun 07 08:01:30 JST 2018
     */
    int insertSelective(Reservation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table reservation
     * @mbg.generated  Thu Jun 07 08:01:30 JST 2018
     */
    List<Reservation> selectByExample(ReservationExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table reservation
     * @mbg.generated  Thu Jun 07 08:01:30 JST 2018
     */
    Reservation selectByPrimaryKey(Long reservationId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table reservation
     * @mbg.generated  Thu Jun 07 08:01:30 JST 2018
     */
    int updateByExampleSelective(@Param("record") Reservation record, @Param("example") ReservationExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table reservation
     * @mbg.generated  Thu Jun 07 08:01:30 JST 2018
     */
    int updateByExample(@Param("record") Reservation record, @Param("example") ReservationExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table reservation
     * @mbg.generated  Thu Jun 07 08:01:30 JST 2018
     */
    int updateByPrimaryKeySelective(Reservation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table reservation
     * @mbg.generated  Thu Jun 07 08:01:30 JST 2018
     */
    int updateByPrimaryKey(Reservation record);
}