package mrs.domain.mapper;

import java.util.List;
import mrs.domain.model.ReservableRoomExample;
import mrs.domain.model.ReservableRoomKey;
import org.apache.ibatis.annotations.Param;

public interface ReservableRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservable_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    long countByExample(ReservableRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservable_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    int deleteByExample(ReservableRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservable_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    int deleteByPrimaryKey(ReservableRoomKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservable_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    int insert(ReservableRoomKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservable_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    int insertSelective(ReservableRoomKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservable_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    List<ReservableRoomKey> selectByExample(ReservableRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservable_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    int updateByExampleSelective(@Param("record") ReservableRoomKey record, @Param("example") ReservableRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservable_room
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    int updateByExample(@Param("record") ReservableRoomKey record, @Param("example") ReservableRoomExample example);
}