package mrs.domain.model;

public class MeetingRoom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.room_id
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    private Long roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.room_name
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    private String roomName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.room_id
     *
     * @return the value of meeting_room.room_id
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    public Long getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.room_id
     *
     * @param roomId the value for meeting_room.room_id
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    public void setRoomId(Long roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.room_name
     *
     * @return the value of meeting_room.room_name
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.room_name
     *
     * @param roomName the value for meeting_room.room_name
     *
     * @mbg.generated Mon Jun 04 20:49:18 JST 2018
     */
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }
}